# Ultralytics YOLO 🚀, AGPL-3.0 license
# Continuous Integration (CI) GitHub Actions tests broken link checker using https://github.com/lycheeverse/lychee
# Ignores the following status codes to reduce false positives:
#   - 401(Vimeo, 'unauthorized')
#   - 403(OpenVINO, 'forbidden')
#   - 429(Instagram, 'too many requests')
#   - 500(Zenodo, 'cached')
#   - 502(Zenodo, 'bad gateway')
#   - 999(LinkedIn, 'unknown status code')

name: Check Broken links

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  links:
    name: Markdown and HTML links
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Check Markdown and HTML links
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --scheme https
            --timeout 60
            --insecure
            --accept 401,403,429,500,502,999
            --exclude-all-private
            --exclude 'https?://(www\.)?(linkedin\.com|twitter\.com|instagram\.com|kaggle\.com|fonts\.gstatic\.com|url\.com)'
            --exclude-path 'docs/zh/**'
            --exclude-path 'docs/es/**'
            --exclude-path 'docs/ru/**'
            --exclude-path 'docs/pt/**'
            --exclude-path 'docs/fr/**'
            --exclude-path 'docs/de/**'
            --exclude-path 'docs/ja/**'
            --exclude-path 'docs/ko/**'
            --exclude-path 'docs/hi/**'
            --exclude-path 'docs/ar/**'
            --header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.183 Safari/537.36"
            './**/*.md'
            './**/*.html'
          fail: true
